#!/usr/bin/perl

use strict;
use warnings;

# use autoflush
$| = 1;

sub contains_argument {
  my $line = shift;

  foreach my $word (@ARGV) {
    if ($line =~ /$word/i) {
      return 1;
    }
  }
  return 0;
}

while (<STDIN>) {
  print $_ unless contains_argument($_);
}

